---
- name: Status docker container
  become: yes
  hosts: webserver
  tasks:
    - name: Install package python-docker
      apt: name=python3-docker
      
    - name: Get info container
      docker_container_info:
        name: portafolio-webserver
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Print the status of the container
      debug:
        msg: "The container status is {{ result.container['State']['Status'] }}"
      when: result.exists
