---
- name: Install Java an net-tools
  become: yes
  hosts: jenkins
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
    - name: Install Java 17 jre
      apt: name=openjdk-17-jre
      
    - name: Install net-tools
      apt: name=net-tools
      
    - name: Ensure java is running with ps
      shell: ps aux | grep java
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
